#!/bin/bash

NAME="PACMAN"
PACMAN="/usr/bin/pacman"
CRIT=20
WARN=10
VERBOSE=
KERNEL=

ok() { echo "${NAME} OK - $1"; exit 0; }
warn() { echo "${NAME} WARNING - $1"; exit 1; }
crit() { echo "${NAME} CRITICAL - $1"; exit 2; }
unknown() { echo "${NAME} UNKNOWN - $1"; exit 3; }
usage() { echo "Usage: $0 [-c NUM] [-w NUM] [-p PACMAN]" 1>&2; exit 1; }

while getopts ":w:c:p:vk" o; do
    case "${o}" in
        w) WARN=${OPTARG} ;;
        c) CRIT=${OPTARG} ;;
        p) PACMAN=${OPTARG} ;;
        v) VERBOSE=1 ;;
        k) KERNEL=1 ;;
        *) usage ;;
    esac
done

[ ${VERBOSE} ] && echo "p:${PACMAN} w:${WARN} c:${CRIT}"

[ ! -x ${PACMAN} ] && unknown "Can not find pacman executable"

${PACMAN} -Sy > /dev/null 
[ $? -ne 0 ] && unknown "Can not update database"

COUNT=`${PACMAN} -Qu | wc -l`
[ $? -ne 0 ] && unknown "Update query failed"

KINST=`${PACMAN} -Q -o /boot/config.txt | rev | cut -f1 -d\  | rev`
KRUN=`uname -r | rev | cut -f2- -d- | rev`

[ ${KINST} != ${KRUN} ] && warn "New Kernel Installed:${KINST} Running:${KRUN}"

[ ${COUNT} -ge ${CRIT} ] && crit "Updates available (${COUNT} > ${CRIT})"
[ ${COUNT} -ge ${WARN} ] && warn "Updates available (${COUNT} > ${WARN})"
[ ${COUNT} -gt 0 ] && ok "Updates available (${COUNT})"

ok "No Updates available"

exit 0
