#!/usr/bin/sh

cd $(dirname $0)/..

BASEDIR=`pwd`
SRCDIR=${BASEDIR}/src
BINDIR=${BASEDIR}/bin
echo BASEDIR = ${BASEDIR}
echo BINDIR = ${BINDIR}
echo SRCDIR = ${SRCDIR}

BUILD_DATE=`date +%Y-%m-%d\ %H:%M`
GITTAG=`git tag | head`
GITCOMMIT=`git log -1 --pretty=oneline`
VERSIONFILE=${SRCDIR}/huginn/version.go

echo Generating Version file
rm -f ${VERSIONFILE}
cat <<EOP > ${VERSIONFILE}
package main
const (
  BUILD_DATE = "${BUILD_DATE}"
  VERSION = "${GITTAG}"
  COMMIT = "${GITCOMMIT}"
  FULL = \`
`git log -1 --pretty=full`
\`
)
EOP

echo Build plugins
(cd ${SRCDIR}/huginn/raven
  for i in plugin-*/*.go ; do
    d=`dirname ${i}`
    p=`basename ${i} .go`
    echo -- Building ${d}
    go build -buildmode=plugin -o ${BINDIR}/plugins/${p}.so ${d}/${p}.go
  done 
)

echo Building huginn
(cd ${SRCDIR}/huginn
  go build -o ${BINDIR}/huginn huginn.go version.go 
  echo -- copy web templates
  rsync -a templates ${BINDIR}
)

echo Build nmapparse
cp ${VERSIONFILE} ${SRCDIR}/nmapparse/
(cd ${SRCDIR}/nmapparse
  go build -o ${BINDIR}/nmapparse nmapparse.go version.go
  echo -- copy base.ini
  rsync -a base.ini ${BINDIR}
)

exit 0
