#!/bin/sh

#   Raven Network Discovery and Monitoring
#   Copyright (C) 2019 John{at}Orthoefer{dot}org
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.


LAST=".last_commit"
BUILD_DATE=`date +%Y-%m-%d\ %H:%M`
GITSHA=`git rev-parse HEAD`
GITBRANCH=`git branch | fgrep \*  | cut -f 2- -d\ `
GITTAG=`git tag | head -1`
GITCOMMIT=`git log -1 --pretty=oneline`

DESTDIR=.
[ $# -gt 0 ] && DESTDIR=$1
VERSIONFILE=${DESTDIR}/version.go

echo ${GITSHA} | diff --brief --new-file - ${LAST} > /dev/null && exit 0

echo Generating Version file
rm -f ${VERSIONFILE}
cat <<EOP > ${VERSIONFILE}
/*
   Raven Network Discovery and Monitoring
   Copyright (C) 2019 John{at}Orthoefer{dot}org

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.

*/
package license
const (
  BUILD_DATE = "${BUILD_DATE}"
  SHA = "${GITSHA}"
  BRANCH = "${GITBRANCH}"
  VERSION = "${GITTAG}"
  COMMIT = "${GITCOMMIT}"
  FULL = \`
`git log -1 --pretty=full`
\`
)
EOP

echo ${GITSHA} > ${LAST}

exit 0
